- name: variables in ansible
  hosts: mongodb
  # This is play level variables, map
  vars:
    COURSE: DevOps
    TRAINER: Srinivas
    DURATION: 110HR
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learning Ansible"
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"