- name: ansible variable data types
  hosts: localhost
  vars:
  - AGE: 30 #number
  - NAME: "Srinivas" #String
  - isDevOps: true #boolean
  - Skills: #list
    - DevOps
    - AWS
    - Docker
  - EXPERIENCE: #map
      DevOps: 7
      AWS: 5
      Docker: 4
  tasks:
  - name: print number variable
    ansible.builtin.debug:
      msg: "{{AGE}}"
  - name: print String variable
    ansible.builtin.debug:
      msg: "{{NAME}}"
  - name: print boolean variable
    ansible.builtin.debug:
      msg: "{{isDevOps}}"
  - name: print list variables
    ansible.builtin.debug:
      msg: "{{Skills}}"
  - name: print Map variable
    ansible.builtin.debug:
      msg: "{{EXPERIENCE}}"
