- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # when you want to run linux commands directly i.e in the case of ansible module not available
    # when the user does not exists, ansible treating this is failure and come out by default
    # ignore_errors: true
    ansible.builtin.command: id roboshop
    register: output # output is variable name
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create user roboshop
    become: yes # we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop
    when: output.rc !=0 #if this expression is true then only this module will run

# assignment: take user name as variable, and then dynamically check user exists or not then create
# assignemnt: chack a directory exists or not, if not exists create it
