- name: install packages
  hosts: mongodb
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx